Adds some extra categories
stpierre/lisa-bingo pull request #3
Opened 2016-11-05 17:03 UTC by cluening

Individual words to hunt for are denoted with quotes around them.

2016-11-07 16:24 UTC, stpierre requested changes

2016-11-07 16:24 UTC, stpierre commented on categories.json
> +    "Google Glass",
Already covered by line 7, "Non-wrist wearable". Remove.

2016-11-07 16:24 UTC, stpierre commented on categories.json
> +    "\"10x\"",
Let's add "20x" too, either as a separate category or as an option here (e.g., `"\"10x\"/\"20x\""`).

2016-11-07 16:24 UTC, stpierre commented on categories.json
> +    "Tinfoil hats",
Literal or figurative?

2016-11-07 16:24 UTC, stpierre commented on categories.json
> +    "\"Devops\"",
This appears in the program, so it's basically a free spot. Let's remove it. (Somewhat incredibly, neither "Noops" nor "as a Service" appear in the program AFAICT.)

2016-11-07 16:24 UTC, stpierre commented on categories.json
> +    "\"as a service\"",
Let's make this `"\"as-a-Service\" abuse\"`. We're guaranteed to hear IaaS and SaaS and so on, but I'm sure some marketroid has a truly egregious *-as-a-Service for us all to laugh at.

2016-11-07 16:24 UTC, stpierre commented on categories.json
> +    "\"Container\"",
"Container" is in the program, please remove.

2016-11-11 04:32 UTC, cluening commented on categories.json
> +    "Tinfoil hats",
Literal, of course.

2016-11-11 04:37 UTC, cluening commented on categories.json
> +    "\"10x\"",
I like adding it separately as something more difficult to get.

2016-12-04 13:59 UTC, merged